version: '3.4'

services:

  CompanyService:
    image: companyservice
    container_name: repapplication-companyservice
    build:
      context: .
      dockerfile: CompanyService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
      ASPNETCORE_URLS: "http://+:5030"
    networks:
      - repapplication_repappnetwork      
      

      
  RepApplicationGateway:
    image: repapplicationgateway
    container_name: repapplication-gateway
    build:
      context: .
      dockerfile: RepApplication.Api.Gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Local"
      ASPNETCORE_URLS: "http://+:5020"
    ports:      
      - "5020:5020"
    networks:
      - repapplication_repappnetwork  

networks:
  repapplication_repappnetwork:
    external: true  